// Every data-testid the journeys use, by page. Specs call
// page.getByTestId(sel.workspace.search); when markup changes, only this file
// changes. Ids are added to internal/web/templates/*.html.tmpl and to the JS
// that renders dynamic rows (static/app.js, compare.js, profiles.js).

export const sel = {
  header: {
    accessBadge: "access-badge",
  },
  connect: {
    driver: "conn-driver",
    host: "conn-host",
    port: "conn-port",
    database: "conn-database",
    user: "conn-user",
    password: "conn-password",
    connect: "conn-connect",
  },
  job: {
    status: "job-status",
    progressCount: "job-progress-count",
    // A summary card of the finished run: "rows", "tables", "objects", ...
    stat: (label: string) => `result-stat-${label}`,
    statValue: "result-stat-value",
  },
  workspace: {
    rail: "ws-rail",
    canvasWrap: "ws-canvas-wrap",
    actionBar: "ws-actionbar",
    canvas: "ws-canvas",
    graphLoading: "ws-graph-loading",
    countsStatus: "ws-counts-status",
    tableCount: "ws-count-total",
    populatedCount: "ws-stat-populated",
    access: "ws-access",
    search: "ws-search",
    searchCount: "ws-search-count",
    matchBar: "ws-match-bar",
    matchLabel: "ws-match-label",
    matchPrev: "ws-match-prev",
    matchNext: "ws-match-next",
    matchOnly: "ws-match-only",
    navigator: "ws-navigator",
    minimapCanvas: "ws-minimap-canvas",
    minimapZoom: "ws-minimap-zoom",
    tabSelected: "ws-tab-selected",
    tabIgnored: "ws-tab-ignored",
    autoCount: "ws-count-auto",
    scope: "ws-scope",
    selectedItem: "ws-selected-item",
    selectedName: "ws-selected-name",
    selectedTag: "ws-selected-tag",
    ignoredRow: "ws-ignored-row",
    ignoredTable: "ws-ignored-table",
    ignoredPattern: "ws-ignored-pattern",
    // Row preview of the table shown in the Table tab (also used by the table modal).
    previewTable: "preview-table",
    mode: (mode: "seed" | "gaps" | "generate" | "clone") => `ws-mode-${mode}`,
    modeWarning: (mode: "seed" | "gaps" | "generate" | "clone") => `ws-mode-warn-${mode}`,
    rows: "ws-rows",
    tuningToggle: "ws-tuning-toggle",
    tuningSummary: "ws-tuning-summary",
    workers: "ws-workers",
    genWorkers: "ws-gen-workers",
    profile: "ws-profile",
    cloneTarget: "ws-clone-target",
    cloneViews: "ws-clone-views",
    cloneRoutines: "ws-clone-routines",
    cloneTriggers: "ws-clone-triggers",
    run: "ws-run",
    runNote: "ws-run-note",
  },
  compare: {
    app: "cmp-app",
    source: "cmp-source",
    target: "cmp-target",
    run: "cmp-run",
    results: "cmp-results",
    stats: "cmp-stats",
    gauge: "cmp-gauge",
    gaugeTable: "cmp-gauge-table",
    gaugeSourceRows: "cmp-gauge-source-rows",
    gaugeTargetRows: "cmp-gauge-target-rows",
    advancedToggle: "cmp-advanced-toggle",
    stopOnError: "cmp-stop",
    exportOpen: "cmp-export",
    exportDialog: "cmp-export-dialog",
    exportPreview: "cmp-export-preview",
    exportDownload: "cmp-export-download",
    exportClose: "cmp-export-close",
    importOpen: "cmp-import",
    importDialog: "cmp-import-dialog",
    importFile: "cmp-import-file",
    importText: "cmp-import-text",
    importUse: "cmp-import-use",
    importStatus: "cmp-import-status",
    importClose: "cmp-import-close",
    plan: "cmp-plan",
    planModal: "cmp-plan-modal",
    planTitle: "cmp-plan-title",
    planRow: "cmp-plan-row",
    planImportedSource: "cmp-plan-imported-source",
    execute: "cmp-execute",
    outcome: "cmp-outcome",
  },
  profiles: {
    app: "pf-app",
    name: "pf-name",
    status: "pf-status",
    save: "pf-save",
    exportOpen: "pf-export",
    ignoreInput: "pf-ignore-input",
    ignoreAdd: "pf-ignore-add",
    ignoreItem: "pf-ignore-item",
    ignoreGlob: "pf-ignore-glob",
    ignoreHits: "pf-ignore-hits",
    ignoreHit: "pf-ignore-hit",
    yamlDownload: "pf-yaml-download",
  },
  runStrip: {
    root: "run-strip",
    status: "run-strip-status",
    failure: "run-strip-failure",
    next: "run-strip-next",
    detail: "run-strip-detail",
  },
  snapshot: {
    open: "ws-snapshot",
    calibrate: "ws-calibrate",
    dialog: "snapshot-dialog",
    preview: "snapshot-preview",
    download: "snapshot-download",
    compare: "snapshot-compare",
  },
  tuning: {
    open: "ws-recommend",
    dialog: "tune-dialog",
    result: "tune-result",
    writers: "tune-writers",
    generators: "tune-generators",
    growth: "tune-growth",
    apply: "tune-apply",
  },
  production: {
    checkbox: "conn-production",
    badge: "conn-production-badge",
    confirmLabel: "conn-confirm-label",
    dialog: "prod-confirm-dialog",
    input: "prod-confirm-input",
    ok: "prod-confirm-ok",
  },
} as const;
