//go:build integration

package integration_test

import (
	"database/sql"
	"fmt"
	"path/filepath"
	"testing"
)

// After seedstorm writes explicit ids, the application inserting its own rows
// must not hit duplicates: Postgres sequences have to be moved past the seeded
// ids (MySQL AUTO_INCREMENT does this on its own; it is checked as a guard).
func sequenceDDL(e engine) []string {
	if e.driver == postgresDriver {
		return []string{
			`CREATE TABLE seq_serial (id SERIAL PRIMARY KEY, name VARCHAR(40) NOT NULL)`,
			`CREATE TABLE seq_identity (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(40) NOT NULL)`,
			`CREATE TABLE seq_child (id SERIAL PRIMARY KEY, parent_id INTEGER NOT NULL, FOREIGN KEY (parent_id) REFERENCES seq_serial(id))`,
		}
	}
	return []string{
		"CREATE TABLE seq_serial (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40) NOT NULL)",
		"CREATE TABLE seq_identity (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(40) NOT NULL)",
		"CREATE TABLE seq_child (id INT AUTO_INCREMENT PRIMARY KEY, parent_id INT NOT NULL, FOREIGN KEY (parent_id) REFERENCES seq_serial(id))",
	}
}

// appInserts performs the inserts an application would: no id, database default.
func appInserts(t *testing.T, conn *sql.DB, when string) {
	t.Helper()
	for i := 0; i < 3; i++ {
		for _, table := range []string{"seq_serial", "seq_identity"} {
			if _, err := conn.Exec(fmt.Sprintf("INSERT INTO %s (name) VALUES ('app row')", table)); err != nil {
				t.Fatalf("%s: application insert into %s failed: %v", when, table, err)
			}
		}
	}
}

func TestSequences_ApplicationInsertsWorkAfterSeedingExplicitIDs(t *testing.T) {
	for _, e := range engines() {
		t.Run(e.name, func(t *testing.T) {
			dsn, conn := e.scratchDB(t, "ss_seq")
			for _, stmt := range sequenceDDL(e) {
				execSQL(t, conn, stmt)
			}
			schemaPath := filepath.Join(t.TempDir(), "schema.yaml")
			runBin(t, "introspect", "--db", e.name, "--dsn", dsn, "--out", schemaPath)

			runBin(t, "seed", "--db", e.name, "--dsn", dsn, "--schema", schemaPath, "--rows", "25")
			appInserts(t, conn, "after seed")

			runBin(t, "seed", "--db", e.name, "--dsn", dsn, "--schema", schemaPath, "--rows", "10")
			appInserts(t, conn, "after a second seed")

			execSQL(t, conn, "DELETE FROM seq_child")
			runBin(t, "gaps", "--db", e.name, "--dsn", dsn, "--schema", schemaPath, "--fill", "--rows", "5", "--yes")
			appInserts(t, conn, "after gaps --fill")
		})
	}
}

func TestSequences_ApplicationInsertsWorkAfterMirror(t *testing.T) {
	for _, e := range engines() {
		t.Run(e.name, func(t *testing.T) {
			srcDSN, src := e.scratchDB(t, "ss_seq_src")
			tgtDSN, tgt := e.scratchDB(t, "ss_seq_tgt")
			for _, stmt := range sequenceDDL(e) {
				execSQL(t, src, stmt)
				execSQL(t, tgt, stmt)
			}
			schemaPath := filepath.Join(t.TempDir(), "schema.yaml")
			runBin(t, "introspect", "--db", e.name, "--dsn", srcDSN, "--out", schemaPath)
			runBin(t, "seed", "--db", e.name, "--dsn", srcDSN, "--schema", schemaPath, "--rows", "40")
			endpoints := []string{"--source-db", e.name, "--source-dsn", srcDSN, "--target-db", e.name, "--target-dsn", tgtDSN}

			runBin(t, append([]string{"mirror"}, endpoints...)...)
			appInserts(t, tgt, "after mirror top-up")

			// Reset truncates with RESTART IDENTITY and re-inserts explicit ids.
			runBin(t, append([]string{"mirror", "--mode", "reset", "--scale", "0.5", "--yes"}, endpoints...)...)
			appInserts(t, tgt, "after mirror reset")
		})
	}
}
